server:
  port: 8091

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:grad_stepup_qa}
    username: ${DB_USERNAME:bj_grad}
    password: ${DB_PASSWORD:}

